---
namespace: pikaviestin
name: matrix
description: Matrix
dependencies:
  community.general: ">=5.0.0"
version: 0.5.0
readme: README.md
repository: https://github.com/pikaviestin/ansible-matrix
license_file: LICENSE
authors:
  - uumas
  - samip5
