---

namespace: pikaviestin
name: matrix
description: Matrix roles
version: 0.1.1
readme: README.md
repository: https://github.com/pikaviestin/ansible-matrix
license_file: LICENSE
authors:
  - uumas
  - samip5
