---

depends: "{{ python_depends }}"

matrix_extra_tasks:
  - pip
  - appservice

pip_packages:
  - 'mautrix-googlechat[all]'

registrationgen_exec: >
  {{ matrix_extra_workdir }}/bin/python -m mautrix_googlechat
  -g
  -r '{{ matrix_extra_workdir }}/appservice-registration.yaml'
  -c '{{ matrix_extra_workdir }}/config.yaml'
exec: >
  {{ matrix_extra_workdir }}/bin/python -m mautrix_googlechat
  -c {{ matrix_extra_workdir }}/config.yaml

mautrix_port: 29320
mautrix_loggers:
  - mau
  - maugclib
  - aiohttp
  - backfill

mautrix_block:
  - provisioning
