---

argument_specs:
  main:
    short_description: Synapse matrix server
    description: >
      Installs and configures a synapse matrix homeserver. Supports workers.
      Supports installation from debian repo or in docker.
    options:
      synapse_install_method:
        description: Installation method
        type: str
        required: false
        default: debrepo
        choices:
          - debrepo

      synapse_psql_user:
        description: Postgres database username for synapse. Defaults to value from psql_dbs['matrix-synapse']['user']
        type: str
        required: "{{ psql_dbs is not defined }}"
      synapse_psql_pw:
        description: Postgres database password for synapse. Defaults to value from psql_dbs['matrix-synapse']['password']
        type: str
        required: "{{ psql_dbs is not defined }}"
      synapse_psql_db:
        description: Postgres database name for synapse
        type: str
        required: false
        default: "{{ synapse_psql_user }}"
      synapse_psql_host:
        description: Postgres database server hostname
        type: str
        required: false
        default: localhost

      synapse_doublepuppet_token:
        description: >
          If defined, sets up a appservice for doublepuppeting, with this token
          allowed to act on behalf of any local user.
        type: str
        required: false
        defulat: ''

      matrix_max_upload_size_mb:
        description: Maximum file upload size for synapse in megabytes
        type: int
        required: false
        default: 100
      matrix_auto_join_rooms:
        description: A list of room aliases new users will be joined to on first login
        type: list
        elements: str
        required: false
        default: []

      matrix_signing_key:
        description: Matrix federation signing key. Will use auto-generated one if not defined.
        type: str
        required: false

      synapse_metrics:
        description: Whether to enable prometheus metrics listener on port 9656 and workers on worker port + 1000
        type: bool
        required: false
        default: false

      synapse_presence:
        description: Whether to enable presence detection on synapse. If disabled all users will be shown as permanently offline.
        type: bool
        required: false
        default: true
