---

- name: Config synapse service
  ansible.builtin.systemd:
    daemon_reload: true
    name: matrix-synapse.service
    enabled: true
  notify: Config matrix target

- name: Config matrix target
  ansible.builtin.systemd:
    daemon_reload: true
    name: matrix.target
    enabled: true
    state: restarted

- name: Restart synapse
  block:
    - name: Restart synapse (systemd)
      ansible.builtin.systemd:
        name: matrix-synapse.service
        state: restarted
      when: synapse_install_method == 'debrepo'

    - name: Restart synapse (docker)
      community.docker.docker_container:
        name: "{{ docker_service_name }}"
        restart: true
      when: synapse_install_method == 'docker'

- name: Disable worker services
  ansible.builtin.systemd:
    name: "matrix-synapse-worker@{{ item }}.service"
    state: stopped
    enabled: false
  loop: "{{ synapse_disable_worker_services }}"

- name: Config worker services
  ansible.builtin.systemd:
    daemon_reload: true
    name: "matrix-synapse-worker@{{ item }}.service"
    enabled: true
  loop: "{{ synapse_worker_services }}"
  notify: Config matrix target

- name: Disable matrix-synchrotrons
  ansible.builtin.systemd:
    daemon_reload: true
    name: matrix-synchrotron@{{ item }}.service
    enabled: false
  loop:
    - balancer
    - init
