---

- name: Config synapse service
  ansible.builtin.systemd:
    daemon_reload: true
    name: matrix-synapse.service
    enabled: true
  notify: Config matrix target

- name: Config matrix target
  ansible.builtin.systemd:
    daemon_reload: true
    name: matrix.target
    enabled: true
    state: restarted

- name: Config worker services
  ansible.builtin.systemd:
    daemon_reload: true
    name: "matrix-synapse-worker@{{ item }}.service"
    enabled: true
  loop: "{{ synapse_worker_services }}"
  notify: Config matrix target
