---

- name: config synapse service
  systemd:
    daemon_reload: yes
    name: matrix-synapse.service
    enabled: yes
  notify: config matrix target

- name: config matrix target
  systemd:
    daemon_reload: yes
    name: matrix.target
    enabled: yes
    state: restarted

- name: config worker services
  systemd:
    daemon_reload: yes
    name: "matrix-synapse-worker@{{ item }}.service"
    enabled: yes
  loop: "{{ synapse_worker_services }}"
  notify: config matrix target
