---

- name: Install latest mautrix-signal release from github releases
  ansible.builtin.get_url:
    url: 'https://github.com/mautrix/signal/releases/latest/download/mautrix-signal-amd64'
    dest: "/opt/mautrix-whatsapp/mautrix-signal"
    mode: '755'

- name: Include appservice tasks
  ansible.builtin.import_tasks: appservice.yml

- name: Chmod registration file
  ansible.builtin.file:
    path: /opt/mautrix-signal/appservice-registration.yaml
    mode: '0644'
