---

- name: Clone git repo for {{ matrix_extra }}
  ansible.builtin.git:
    repo: "{{ matrix_extra_git_repo }}"
    dest: /opt/{{ matrix_extra }}/src
    force: true

- name: Install {{ matrix_extra }}
  community.general.npm:
    path: /opt/{{ matrix_extra }}/src
  register: install
  notify: Restart matrix target
