---

- name: Add user to signald group - {{ matrix_extra }}
  ansible.builtin.user:
    name: "{{ matrix_extra }}"
    groups: signald
    append: true
  become_user: root

- name: Set signald directory permissions
  ansible.builtin.file:
    path: /var/lib/signald/{{ item }}
    state: directory
    owner: signald
    group: signald
    mode: 0770
  loop:
    - data
    - attachments
    - avatars
  become_user: signald

- name: Copy /etc/default/signald env
  ansible.builtin.template:
    src: signald-env
    dest: /etc/default/signald
    mode: 0755
  become_user: root
