---

- name: Ensure draupnir dependencies are installed
  ansible.builtin.apt:
    name:
      - yarn
      - nodejs
    state: present

- name: Create user
  ansible.builtin.user:
    name: draupnir
    shell: /bin/nologin
    home: "{{ matrix_bot_draupnir_data_path }}"
    system: true
    create_home: true


- name: Clone the source code
  become: true
  become_user: draupnir
  ansible.builtin.git:
    repo: "https://github.com/the-draupnir-project/Draupnir.git"
    # renovate: datasource=github-releases depName=the-draupnir-project/draupnir
    version: "v2.2.0"
    dest: "{{ matrix_bot_draupnir_data_path }}/src"

- name: Check current permissions
  ansible.builtin.stat:
    path: "{{ matrix_bot_draupnir_data_path }}"
  register: draupnir_stat

- name: Make sure permissions are right
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: "chown -R draupnir:draupnir {{ matrix_bot_draupnir_data_path }}"
  when: draupnir_stat.stat.pw_name != "draupnir" or draupnir_stat.stat.gr_name != "draupnir"

- name: corepack enable
  become: true
  become_user: root
  ansible.builtin.command:
    cmd: "corepack enable"

- name: Yarn install
  become: true
  become_user: draupnir
  ansible.builtin.command:
    cmd: "yarn install"
    chdir: "{{ matrix_bot_draupnir_data_path }}/src"

- name: Yarn build
  become: true
  become_user: draupnir
  ansible.builtin.command:
    cmd: "yarn build"
    chdir: "{{ matrix_bot_draupnir_data_path }}/src"
