---

- name: Ensure signing key matches matrix_signing_key variable
  ansible.builtin.copy:
    content: "{{ matrix_signing_key }}"
    dest: /etc/matrix-synapse/homeserver.signing.key
    owner: matrix-synapse
    group: nogroup
    mode: '0600'
  when: matrix_signing_key is defined

- name: Ensure signing key permissions set correctly
  ansible.builtin.file:
    path: /etc/matrix-synapse/homeserver.signing.key
    state: file
    owner: matrix-synapse
    group: nogroup
    mode: '0600'
  when: matrix_signing_key is not defined

- name: Ensure synapse configs are in place
  ansible.builtin.template:
    src: conf.d/{{ item }}.yaml.j2
    dest: /etc/matrix-synapse/conf.d/{{ item }}.yaml
    owner: matrix-synapse
    group: nogroup
    mode: '0644'
  loop:
    - listeners
    - server_name
    - url_preview
    - autojoin
  notify: Config matrix target

- name: Ensure synapse configs including secrets is in place
  ansible.builtin.template:
    src: conf.d/{{ item }}.yaml.j2
    dest: /etc/matrix-synapse/conf.d/{{ item }}.yaml
    owner: matrix-synapse
    group: nogroup
    mode: '0600'
  loop:
    - database
    - general
  notify: Config matrix target

- name: Ensure password provider config is in place
  ansible.builtin.template:
    src: conf.d/password_providers.yaml.j2
    dest: /etc/matrix-synapse/conf.d/password_providers.yaml
    owner: matrix-synapse
    group: nogroup
    mode: '0644'
  when: synapse_ldap_servers is defined
  notify: Config matrix target

- name: Ensure sso config is in place
  ansible.builtin.template:
    src: conf.d/sso.yaml.j2
    dest: /etc/matrix-synapse/conf.d/sso.yaml
    owner: matrix-synapse
    group: nogroup
    mode: '0644'
  when: matrix_openidc_providers is defined
  notify: Config matrix target

- name: Ensure turn config is in place
  ansible.builtin.template:
    src: conf.d/turn.yaml.j2
    dest: /etc/matrix-synapse/conf.d/turn.yaml
    owner: matrix-synapse
    group: nogroup
    mode: '0644'
  when: turn_domain is defined
  notify: Config matrix target

- name: Configure doublepuppet appservice
  when: synapse_doublepuppet_token | length > 0
  block:
    - name: Ensure doublepuppet registration is in place
      ansible.builtin.template:
        src: doublepuppet-registration.yaml.j2
        dest: /etc/matrix-synapse/doublepuppet-registration.yaml
        owner: matrix-synapse
        group: nogroup
        mode: '0600'
      notify: Config matrix target

    - name: Ensure appservice config file present
      ansible.builtin.lineinfile:
        path: /etc/matrix-synapse/conf.d/appservice.yaml
        line: 'app_service_config_files:'
        regexp: '^app_service_config_files: *?$'
        create: true
        mode: 0644
        insertbefore: BOF
      notify: Config matrix target

    - name: Configure doublepuppet appservice
      ansible.builtin.lineinfile:
        path: '/etc/matrix-synapse/conf.d/appservice.yaml'
        line: "  - '/etc/matrix-synapse/doublepuppet-registration.yaml'"
        regexp: '^.*doublepuppet.*$'
      notify: Config matrix target
