---
- name: Ensure synapse configs are in place
  ansible.builtin.template:
    src: conf.d/{{ item }}.yaml.j2
    dest: /etc/matrix-synapse/conf.d/{{ item }}.yaml
    mode: "644"
  loop:
    - database
    - general
    - listeners
    - server_name
    - url_preview
  notify: Config matrix target

- name: Ensure autojoin config is in place
  ansible.builtin.template:
    src: conf.d/autojoin.yaml.j2
    dest: /etc/matrix-synapse/conf.d/autojoin.yaml
    mode: "644"
  when: matrix_auto_join_rooms is defined
  notify: Config matrix target

- name: Ensure password provider config is in place
  ansible.builtin.template:
    src: conf.d/password_providers.yaml.j2
    dest: /etc/matrix-synapse/conf.d/password_providers.yaml
    mode: "644"
  when: synapse_ldap_servers is defined
  notify: Config matrix target

- name: Ensure modules config is in place
  ansible.builtin.template:
    src: conf.d/modules.yaml.j2
    dest: /etc/matrix-synapse/conf.d/modules.yaml
    mode: "644"
  when: synapse_shared_secret_auth is defined
  notify: Config matrix target

- name: Ensure sso config is in place
  ansible.builtin.template:
    src: conf.d/sso.yaml.j2
    dest: /etc/matrix-synapse/conf.d/sso.yaml
    mode: "644"
  when: matrix_openidc_providers is defined
  notify: Config matrix target

- name: Ensure turn config is in place
  ansible.builtin.template:
    src: conf.d/turn.yaml.j2
    dest: /etc/matrix-synapse/conf.d/turn.yaml
    mode: "644"
  when: turn_domain is defined
  notify: Config matrix target
