---

- name: Ensure signing key matches matrix_signing_key variable
  ansible.builtin.copy:
    content: "{{ matrix_signing_key }}"
    dest: "{{ synapse_config_path }}/homeserver.signing.key"
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0600'
  when: matrix_signing_key is defined

- name: Ensure signing key permissions set correctly
  ansible.builtin.file:
    path: "{{ synapse_config_path }}/homeserver.signing.key"
    state: file
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0600'
  when: matrix_signing_key is not defined

- name: Ensure synapse configs are in place
  ansible.builtin.template:
    src: conf.d/{{ item }}.yaml.j2
    dest: "{{ synapse_config_path }}/conf.d/{{ item }}.yaml"
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0644'
  loop:
    - listeners
    - server_name
    - url_preview
    - autojoin
  notify: Config matrix target

- name: Ensure synapse configs including secrets is in place
  ansible.builtin.template:
    src: conf.d/{{ item }}.yaml.j2
    dest: "{{ synapse_config_path }}/conf.d/{{ item }}.yaml"
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0600'
  loop:
    - database
    - general
  notify: Config matrix target

- name: Ensure password provider config is in place
  ansible.builtin.template:
    src: conf.d/password_providers.yaml.j2
    dest: "{{ synapse_config_path }}/conf.d/password_providers.yaml"
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0644'
  when: synapse_ldap_servers is defined
  notify: Config matrix target

- name: Ensure sso config is in place
  ansible.builtin.template:
    src: conf.d/sso.yaml.j2
    dest: "{{ synapse_config_path }}/conf.d/sso.yaml"
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0644'
  when: matrix_openidc_providers is defined
  notify: Config matrix target

- name: Ensure turn config is in place
  ansible.builtin.template:
    src: conf.d/turn.yaml.j2
    dest: "{{ synapse_config_path }}/conf.d/turn.yaml"
    owner: "{{ synapse_user }}"
    group: nogroup
    mode: '0644'
  when: turn_domain is defined
  notify: Config matrix target
