---


- name: Put synapse configs in place
  template:
    src: "conf.d/{{ item }}.yaml.j2"
    dest: "/etc/matrix-synapse/conf.d/{{ item }}.yaml"
    mode: '644'
  loop:
    - database
    - general
    - listeners
    - server_name
    - url_preview
  notify: config matrix target

- name: autojoin config
  template:
    src: 'conf.d/autojoin.yaml.j2'
    dest: '/etc/matrix-synapse/conf.d/autojoin.yaml'
    mode: '644'
  when: matrix_auto_join_rooms is defined
  notify: config matrix target

- name: password provider config
  template:
    src: 'conf.d/password_providers.yaml.j2'
    dest: '/etc/matrix-synapse/conf.d/password_providers.yaml'
    mode: '644'
  when: synapse_ldap_servers is defined 
  notify: config matrix target

- name: modules config
  template:
    src: 'conf.d/modules.yaml.j2'
    dest: '/etc/matrix-synapse/conf.d/modules.yaml'
    mode: '644'
  when: synapse_shared_secret_auth is defined
  notify: config matrix target

- name: sso config
  template:
    src: 'conf.d/sso.yaml.j2'
    dest: '/etc/matrix-synapse/conf.d/sso.yaml'
    mode: '644'
  when: matrix_openidc_providers is defined
  notify: config matrix target

- name: turn config
  template:
    src: 'conf.d/turn.yaml.j2'
    dest: '/etc/matrix-synapse/conf.d/turn.yaml'
    mode: '644'
  when: turn_domain is defined
  notify: config matrix target
