---

- name: Install dependencies
  apt:
    name:
      - lsb-release
      - wget
      - apt-transport-https
      - python3-pysaml2
      - python3-psycopg2
      - acl

- name: Add matrix.org repo signing key
  apt_key:
    url: 'https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg'
    id: 'AAF9AE843A7584B5A3E4CD2BCF45A512DE2DA058'

- name: Add matrix.org repo
  apt_repository:
    repo: "deb https://packages.matrix.org/debian/ {{ ansible_distribution_release }} main"

- name: Install synapse
  apt:
    name: matrix-synapse-py3
    state: latest

- name: Install redis
  apt:
    name: redis-server
  when: synapse_workers is defined
