---

- name: Include synapse installation tasks
  ansible.builtin.include_tasks: "install_{{ synapse_install_method }}.yml"

- name: Include synapse configuration tasks
  ansible.builtin.import_tasks: config.yml

- name: Include synapse worker tasks
  ansible.builtin.include_tasks: workers.yml
  when: synapse_workers is defined

- name: Run handlers for synapse now
  ansible.builtin.meta: flush_handlers
