---

- name: Fail if not debian
  ansible.builtin.fail:
  when: ansible_os_family != "Debian"

- name: Include debian synapse installation tasks
  ansible.builtin.include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Include synapse configuration tasks
  ansible.builtin.import_tasks: config.yml

- name: Ensure matrix-synapse-shared-secret-auth is the latest version
  ansible.builtin.pip:
    name: git+https://github.com/devture/matrix-synapse-shared-secret-auth
    state: latest
    virtualenv: /opt/venvs/matrix-synapse
  notify: Config synapse service
  when: synapse_shared_secret_auth is defined

- name: Ensure synapse systemd units in place
  ansible.builtin.template:
    src: systemd/{{ item }}.j2
    dest: /etc/systemd/system/{{ item }}
    mode: 0644
  loop:
    - matrix-synapse.service
    - matrix.target
  notify:
    - Config synapse service
    - Config matrix target

- name: Include synapse worker tasks
  ansible.builtin.include_tasks: workers.yml
  when: synapse_workers is defined

- name: Run handlers for synapse now
  ansible.builtin.meta: flush_handlers
