---

- name: Ensure matrix-synchrotron user not present
  ansible.builtin.user:
    name: matrix-synchrotron
    state: absent
    remove: true

- name: Ensure matrix-synchrotron unit not present
  ansible.builtin.file:
    path: /etc/systemd/system/matrix-synchrotron@.service
    state: absent
  notify: Disable matrix-synchrotrons
