---

- name: Set worker type variable
  ansible.builtin.set_fact:
    worker_type: "{{ synapse_worker.key }}"

- name: Include default variables
  ansible.builtin.include_vars: defaults.yml

- name: Include variables for {{ worker_type }}
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ worker_type }}.yml"
      skip: true

- name: Reset worker_ports variable
  ansible.builtin.set_fact:
    worker_ports: []
- name: Set worker_ports variable
  ansible.builtin.set_fact:
    worker_ports: "{{ synapse_worker.value }}"
  when: synapse_worker.value is iterable

- name: Include worker instance tasks for {{ worker_type }}
  ansible.builtin.include_tasks: worker_instance.yml
  loop: "{{ worker_ports }}"
  loop_control:
    loop_var: worker_port
    index_var: worker_index
  when: worker_ports|length != 0

- name: Include worker instance tasks for {{ worker_type }}
  ansible.builtin.include_tasks: worker_instance.yml
  when: worker_ports|length == 0

- name: Append synchrotron variable
  ansible.builtin.set_fact:
    synapse_synchrotrons: "{{ synapse_synchrotrons + [synchrotron_type] }}"
  when: synchrotron_type is defined and synchrotron_type not in synapse_synchrotrons
