---

- name: Ensure synapse-wide worker config in place
  ansible.builtin.template:
    src: conf.d/workers.yaml.j2
    dest: /etc/matrix-synapse/conf.d/workers.yaml
    mode: 0644

- name: Ensure worker systemd unit in place
  ansible.builtin.template:
    src: systemd/matrix-synapse-worker@.service.j2
    dest: /etc/systemd/system/matrix-synapse-worker@.service
    mode: 0644
  notify: Config worker services

- name: Ensure worker config directories exist
  ansible.builtin.file:
    path: /etc/matrix-synapse/{{ item }}
    state: directory
    mode: 0755
  loop:
    - workers
    - worker-logs

- name: Initialize synapse worker vars
  ansible.builtin.set_fact:
    synapse_worker_services: []
    synapse_synchrotrons: []

- name: Ensure worker pidfile dir in /run exists
  ansible.builtin.file:
    path: /run/matrix-synapse/
    state: directory
    owner: matrix-synapse
    group: nogroup
    mode: 0755

- name: Ensure tmpfiles config for pidfile dir in place
  ansible.builtin.template:
    src: tmpfiles-matrix-synapse.conf.j2
    dest: /etc/tmpfiles.d/matrix-synapse.conf
    mode: 0644

- name: Configure workers
  ansible.builtin.include_tasks: worker_type.yml
  loop: "{{ synapse_workers | dict2items }}"
  loop_control:
    loop_var: synapse_worker

- name: Ensure synchrotron balancer removed (legacy)
  ansible.builtin.include_tasks: matrix-synchrotrons.yml
  when: synapse_synchrotrons | length != 0
