---
name: "Publish Collection"

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'galaxy.yml'

jobs:
  publish-collection:
    name: Publish Collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
