---
name: "Publish Collection"

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'galaxy.yml'

jobs:
  publish-collection:
    name: Publish Collection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Ansible Publish
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: "${{ secrets.GALAXY_API_KEY }}"
